### ISSUE TITLE
[BUG] Links in changelog.md display don't work

### ISSUE THREAD

**Issue by osm0sis** [Fox2Code/FoxMagiskModuleManager#132]
Just noticed your app correctly prefers an update.json and changelog.md module download when a module has one, which is great!

Unfortunately some markdown functionality is missing in the changelog.md display, so no links are able to be pressed.

Thanks for the ongoing work!

**Comment by Fox2Code** [comment]
Wait did I think I forgot to add an obvious piece of code, I'll fix it quickly in `0.4.4` as I already know what I forgot.
The worse thing is that I already fixed this bug for module info, but I 

Related pieces off code:
https://github.com/Fox2Code/FoxMagiskModuleManager/blob/master/app/src/main/java/com/fox2code/mmm/markdown/MarkdownUrlLinker.java -> `urlLinkify`
https://github.com/Fox2Code/FoxMagiskModuleManager/blob/master/app/src/main/java/com/fox2code/mmm/manager/LocalModuleInfo.java -> `checkModuleUpdate`
https://github.com/Fox2Code/FoxMagiskModuleManager/blob/master/app/src/main/java/com/fox2code/mmm/ActionButtonType.java -> `localModuleInfo.updateChangeLog`

Since I'm going to bed I'm going to fix that tomorrow, and if you make a PR before I fix the bug tomorrow I would be happy to merge it.

**Comment by Fox2Code** [comment]
Thanks for reporting, was very stupid mistake I made.

**Comment by Fox2Code** [comment]
https://t.me/Fox2Code_Chat

**Comment by osm0sis** [comment]
Still doesn't seem to be working in 0.4.4 in my testing, unfortunately.

**Comment by Fox2Code** [comment]
Give me a test module please.

**Comment by osm0sis** [comment]
Any of mine will show the issue.

https://github.com/Magisk-Modules-Repo/busybox-ndk

```
{
    "version": "1.34.1",
    "versionCode": "13412",
    "zipUrl": "https://forum.xda-developers.com/attachments/update-busybox-installer-v1-34-1-all-signed-zip.5564955/",
    "changelog": "https://raw.githubusercontent.com/Magisk-Modules-Repo/busybox-ndk/master/README.md"
}
```

**Comment by osm0sis** [comment]
Also not sure if you're following this yet, but per the Magisk spec the changelog.md is only 1000 characters (including raw markdown).

**Comment by Fox2Code** [comment]
Yeah I follow this already, the raw document is trimmed to 1000 characters, the https link markdown injection is done after trimming.

**Comment by Fox2Code** [comment]
Well this seems weird, the module declare all links correctly, the URL link adder should not be necessary for your module.
https://raw.githubusercontent.com/Magisk-Modules-Repo/busybox-ndk/master/README.md

**Comment by Fox2Code** [comment]
Fixed, had to browse Android source code tho.
Link were displaying correctly bot just not opening browsers because neither `setMarkdown` or `setParsedMarkdown` was called.

**Comment by osm0sis** [comment]
Thanks! Not sure why the json fallback entry though, master/update.json is probably pretty common, and all my modules have it and already displayed and functioned otherwise fine, links notwithstanding. 🙃

**Comment by Fox2Code** [comment]
I add them so if an older version of `busybox-ndk` that doesn't have `jsonUpdate` is installed, it will show the update anyway.
Since it's a fallback it will always prefer to use module `jsonUpdate` if possible.

**Comment by osm0sis** [comment]
Ahh, that's awesome. ...care to add my others? 😘

https://github.com/search?q=org%3AMagisk-Modules-Repo+osm0sis+xda-developers+in%3AREADME+topic%3Aosm0sis

**Comment by Fox2Code** [comment]
I used a loop for modules fallback, see: https://github.com/Fox2Code/FoxMagiskModuleManager/commit/2d6e5dbbfb15edbba34aa577df8e7b312e34a8ed
